### ISSUE TITLE
shadowing warning with KP in nested context

### ISSUE THREAD

**Issue by tpolecat** [non/kind-projector#20]
Nested use of KP produces a shadowing warning. Maybe allocate new names per compilation unit or something?

```
scala> val x: Monad[Free[Coyoneda[Option,?],?]] = null
warning: type parameter X_kp1 defined in type L_kp shadows type X_kp1 defined in type L_kp. You may want to rename your type parameter, or possibly remove it.
...
```

**Comment by non** [comment]
I can't reproduce that issue on master. I don't see an obvious problem with shadowing, but it sounds like others have seen this too.

I'd love to get a new example that fails with KP but succeeds with type projections (along with the error message and version of Scala). If it can be expressed as a standalone Scala file (similar to [this](https://github.com/non/kind-projector/blob/master/src/test/scala/bounds.scala)) then that would be even better.

**Comment by TomasMikula** [comment]
I, too, have a lot of these warnings in my codebase.

> I don't see an obvious problem with shadowing

The only problem with that is that it prevents enabling `-Xfatal-warnings`.

Here is a stand-alone Scala file:

```scala
import scala.language.higherKinds

object KindProjectorWarnings {
  trait Foo[F[_], A]
  trait Bar[A, B]

  def f[G[_]]: Unit = ()

  f[Foo[Bar[Int, ?], ?]] // shadowing warning
}
```

and compiler output:

```
[warn] /[...]/KindProjectorWarnings.scala:9: type parameter β defined in type Λ$ shadows type β defined in type Λ$. You may want to rename your type parameter, or possibly remove it.
[warn]   f[Foo[Bar[Int, ?], ?]] // shadowing warning
[warn]         ^
```

Not sure what you mean by "but succeeds with type projections"; if I were to write it by hand, I would just not re-use the same parameter name `β` twice.

**Comment by TomasMikula** [comment]
Tried out the new version and the warnings are gone. Thanks!
