### ISSUE TITLE
Release 2.12.0-RC1

### ISSUE THREAD

**Issue by BennyHill** [non/kind-projector#34]
Thanks!

**Comment by non** [comment]
I released 0.8.2 which should support 2.12.0-RC1. Is it not working for you? Let me know if you've encountered problems resolving it, or any other issues.

https://github.com/non/kind-projector#using-the-plugin

**Comment by non** [comment]
Also the newly-released 0.9.0 supports 2.12.0-RC1 as well.

**Comment by BennyHill** [comment]
Thanks!
