### ISSUE TITLE
Consider using pcplod for testing

### ISSUE THREAD

**Issue by non** [non/kind-projector#40]
As per a conversation with @fommil in `typelevel/general`, consider adding some tests with this [pcplod](https://github.com/ensime/pcplod). If we did this, we'd want to add a new submodule (e.g. testing) that would be unpublished and would run the tests.

Benefits:
1. We'd be verifying that the presentation compiler works with _kind-projector_.
2. Provides another method of ensuring the transformations happen as expected.
3. Policy of only adding rewrites that work in the presentation compiler.

Drawbacks:
1. Adding dependencies on both pcplod and a testing framework.
2. Blocks kind-projector progress based on presentation compiler status.

Overall I think it's worth exploring. Worst-case we set these tests up and later decide to disable them. Since kind-projector runs so early I think it's unlikely that we'd become majorly blocked on PC issues (but you never know).

**Comment by dwijnand** [comment]
Note you can also avoid a testing framework by just having a main() that runs the pcplod tests.

Or you could use JUnit.

**Comment by fommil** [comment]
I think even having an `ignored` test is valuable because at least we have a clear reproduction of a bug *somewhere*.

**Comment by fommil** [comment]
https://gist.github.com/yilinwei/0c78c6de7ed62741f15385439e23196d
