### ISSUE TITLE
Hi, I am reading the code, a little confused...

### ISSUE THREAD

**Issue by MarisaKirisame** [non/kind-projector#42]
So at https://github.com/non/kind-projector/blob/master/src/main/scala/KindProjector.scala#L317
you use cache to avoid recomputation.
What confuse me is, why cant you use the cache at the start of transform? If I get it correctly, (if you have cache result it is already correct), so why spent extra time rechecking?

**Comment by non** [comment]
Hi @MarisaKirisame,

The `transform` method starts on line 149 and the `treeCache.get(tree)` you mention is on line 317. All the code between those lines consists of definitions for inner methods. That code does not *do* anything until it is invoked, which occurs after line 317 (e.g. `validateLambda` at 331 or `handlePlaceholder` at 339).

Does that make sense? I think the use of the cache is the first thing that actually *happens* when `transform` is called.

**Comment by MarisaKirisame** [comment]
Yeah, sry, it's hard to see indent correctly on github...
