### ISSUE TITLE
publish for Scala 2.13.0-M3, please?

### ISSUE THREAD

**Issue by SethTisue** [non/kind-projector#63]
this plugin is a prerequisite before both scalaz and pretty much the whole Typelevel ecosystem can publish

@non wrote on the similar ticket for M2:

> I'm looking into this -- I think I may have to disable the pcplod tests since I don't think that is available for 2.13.0-M2.

yeah, I wouldn't wait for pcplod — https://github.com/ensime/pcplod/pull/28 was closed today without explanation

**Comment by xuwei-k** [comment]
https://github.com/non/kind-projector/pull/62

**Comment by TomasMikula** [comment]
Just released version 0.9.6 for 2.13.0-M3.
