### ISSUE TITLE
Multiple-level projectors `?`

### ISSUE THREAD

**Issue by diesalbla** [non/kind-projector#69]
With `?` you can generate a parametric type alias, projected on the position of `?`. For example:
```Scala
Either[Int, ?]          // equivalent to: type R[+A] = Either[Int, A]
```
This  only works at one nesting level. If you have more than one nesting level, for instance if you want something like `List[Either[Int, A]]`, then the `?` does not work:
```Scala
List[Either[Int, A]] // equivalent to List[ ({type L[x] = Either[Int, X]})#L ]
```
For this case, kind-projector provides the following syntax:
```Scala
λ[α => List[Either[Int, α]]
Lambda[A => List[Either[Int, A]]
```
The first one is clear enough (after a while), but, while I am all for using and reading Unicode characters, it is not easy to remember the key-binding to write them. The second one is too verbose.

#### Proposal 

I would like to suggest adding extra symbols to represent the notion of `?`, but for two or more nesting levels of type-constructor application. For example, use two question-marks `??` to bind two levels out:

```Scala
List[Either[Int, ?? ]]   // equivalent to: type R[A] = List[Either[Int, A]]
```
This solution would still be mostly syntactic (it only has to detect a nested type-constructor application).

**Comment by TomasMikula** [comment]
> while I am all for using and reading Unicode characters, it is not easy to remember the key-binding to write them.

I recommend installing Greek keyboard layout. 😉 
Alternatively, many editors let you set up automatic rewrites, say `\lambda` to `λ`.

Note that in addition to deeper nesting, the general notation also handles multiple (or zero) mentions of a variable, or changing the order of variables:

```scala
λ[a => (a, a)]
λ[a => Int]
λ[(a, b) => Function1[b, a]]
```

So we would still have to use the `λ` form in some cases.

I think the deeper the nesting is, the more preferable the λ form is, because named variables are easier to read than counting the levels of nesting.

That said, I'm not opposed to some such feature if implemented well, I just don't think it buys us much.

Also note that [dotty's type lambdas](http://dotty.epfl.ch/docs/reference/type-lambdas.html) don't have any shorthand syntax at the moment.

**Comment by non** [comment]
I agree with @TomasMikula here.

Given that `???` already has a different meaning in Scala, I don't think we could really generalize beyond the "two-level" version. Given that the `?` syntax is already a special case of the generalized type lambda syntax, this would be a special case of a special case.

So in summary, I don't feel like there is enough payoff for this feature, and I'm a bit skeptical it would be worth the effort. That said if we get a lot of requests for something like this it might be worth revisiting.

**Comment by diesalbla** [comment]
> I think the deeper the nesting is, the more preferable the λ form is, because named variables are easier to read than counting the levels of nesting.

The proposed notation would only be used for cases in which you have one variable, with one mention, but nested several levels. You find this often in code using monad transformers, where you may end up with a type expression made up of stacked type multi-parameter type constructors. Nevertheless, I partially agree with you that, at some point, the `?` notation become less convenient than the Lambda notation, or than a type alias.  

@non, @TomasMikula: Anyway, thanks for giving the proposal a thought.

**Comment by fommil** [comment]
wow this is crazy, @diesalbla, I was thinking almost the same thing (see the linked ticket). BTW, I have `yassnippet` set up to expand some greek letters with `m-TAB` :smile: but I would like a better solution. Alternatively you can just type the names and leave them long-form in the code but render then with `prettify-symbol` https://gitlab.com/fommil/emacs-prettify-greek (particularly useful when working in financial option pricing...)

**Comment by diesalbla** [comment]
It seems this does not have enough traction. I also understand that there is a discussion for a similar syntax in Dotty, which could make this even less likely. I am thus withdrawing.
