### ISSUE TITLE
Type parameter list lambda for *->*

### ISSUE THREAD

**Issue by barambani** [non/kind-projector#77]
Is there a way to do something like 
```scala
def something[E, F[_] : ApplicativeError[OptionT[?[_], ?], E]](): F = ???
```
I tried the above and also the following but no joy yet
```scala
def something[E, A, F[_] : ApplicativeError[OptionT[?[_], A], E]](): F = ???
```

```scala
def something[E, F[_] : λ[α[_] => ApplicativeError[OptionT[α, ?], E]]](): F = ???
```

```scala
def something[E, A, F[_] : λ[α[_] => ApplicativeError[OptionT[α, A], E]]](): F = ???
```
There is an easy work-around for this but I was just wondering if there is a way to do it in the type parameter list instead of the implicit value parameter list. 
Thanks for this amazing library by the way.

**Comment by TomasMikula** [comment]
The third way would be the correct way, except `F` is not a valid (return) type. After changing the return type to `F[Unit]`, it works for me:

```scala
scala> def something[E, F[_] : λ[α[_] => ApplicativeError[OptionT[α, ?], E]]](): F[Unit] = ???
something: [E, F[_]]()(implicit evidence$1: ApplicativeError[[β$0$]OptionT[F,β$0$],E])F[Unit]

scala> 
```

**Comment by barambani** [comment]
Thanks for the clarification. Now that I look, the third version works perfectly as you suggest, and the error was something even sillier than the return type and I corrected it without noticing while reducing the expression in the example above

![paris_tuileries_garden_facepalm_statue](https://user-images.githubusercontent.com/201339/42753498-09d0ab6e-88e9-11e8-96ef-de6746446d5a.jpg)

thanks a lot. It works like a charm. I'm closing this.
