### ISSUE TITLE
enable Travis-CI in this repo

### ISSUE THREAD

**Issue by SethTisue** [non/kind-projector#93]
the repo has a `.travis.yml` file, but it doesn't do anything because Travis-CI isn't enabled. it needs to be enabled by a repo admin by visiting https://travis-ci.org/non/kind-projector

**Comment by TomasMikula** [comment]
Thank you! We will have to wait for @non, I don't have the rights to do it.

**Comment by non** [comment]
I'll go ahead and do this (and will also add rights for @TomasMikula).

**Comment by non** [comment]
OK, it should be enabled now.

**Comment by non** [comment]
(BTW, I don't see a way to add rights for @TomasMikula, sorry!)

**Comment by SethTisue** [comment]
trying it out at https://github.com/non/kind-projector/pull/95
